### ISSUE TITLE
Unable to access added services

### ISSUE THREAD

**Issue by gkerickson** [btopro/elmsln#48]
When trying to access a newly generated course outline I receive an access denied message. I have made the course as open as I can, is this due to a setting for the course in the CIS?

https://courses.lawclinics.wisc.edu/first/

**Comment by btopro** [comment]
This is because you leave one drupal site and go to another. This is the default behavior unless there's a single sign on system in place. In the vagrant setup, it has the bakery module enabled and configured by default to provide the automatic login on demand, keeping your access happy across all the domains.  At PSU, we have Cosign / Webaccess. This is where you guys will have Shib configured to keep the user logged in across multiple systems for a seamless UX no matter what DB they happen to be having serve up the page.

For now, ssh into the server and issue: `d @courses.first uli` to generate a one time login link for your account. You can use this to log in prior to getting SSO up and running.
