### ISSUE TITLE
Adding new modules

### ISSUE THREAD

**Issue by gkerickson** [btopro/elmsln#49]
How can I add a module to all of my sites at once? Individually? Can I add a module to just one instance of a service or do all courses using the same service have to have that same module?

**Comment by btopro** [comment]
So one of the principles of ELMSLN is to keep "core" abstracted from "config". In our system we consider config basically anything that happens after its installed. So, sites are requested, the system is installed, modules added, any of this is "config" by our definition.  As a result, all projects / settings.php's .htaccess files, etc are symlinked into scope of the different drupal systems via the config directory.

https://github.com/btopro/elmsln-config-example provides an example configuration directory, if you look at this, you'll see it largely mirrors the structure of the main elmsln repo.

To add a module into the setup, you'll want to SFTP the module into /var/www/elmsln/config/shared/drupal-7.x/modules. If it's a contrib module, i'd recommend putting it in a folder in there called contrib. If it's something you are authoring for the deployment, custom.

This then gets symlinked into the scope of all the different tools in ELMSLN so that you could find the files (not that it really matters) at something like the following example:

module named shib_auth will then appear in...
/var/www/elmsln/core/dslmcode/stacks/online/sites/all/modules/_my_modules/contrib/shib_auth

because the _my_modules directory symlinks over to /var/www/elmsln/config/shared/drupal-7.x/modules
