### ISSUE TITLE
LRS / tin-can API intergration

### ISSUE THREAD

**Issue by btopro** [btopro/elmsln#62]
There appears to be some work started in this sandbox project. Can't speak to it working but looks like a decent start - https://www.drupal.org/node/1829346#comment-9784629

**Comment by rickhumphries** [comment]
We've got things going in this area already. We've successfully set up the ability to manually send xAPI statements to learning locker on behalf of one (or a group of) students, and automatically send statements to learning locker after completing a H5P activity. This hasn't used any existing Drupal projects though but should be ready to release in the next few weeks.

**Comment by btopro** [comment]
You make me so happy sometimes

**Comment by mkwisc** [comment]
That's awesome @rickhumphries ! Are there plans to make this part of ELMSLN (like piwik or the media system)? Having an easy way to get the LRS up and running, even if not directly in ELMSLN, would be great as it currently doesn't seem to be so easy. It will also be great to see examples of how this works in the near future.

**Comment by btopro** [comment]
http://learninglocker.net/

**Comment by rickhumphries** [comment]
We're running Learning Locker separately though it still follows the same url naming convention as media/pwik etc. I'm told the setup is a bit fiddly but perhaps the learning locker team will make this easier in the future. I'm doing some testing on our first prototype currently so once I've got some solid workflow examples I'll try and record a video to show

**Comment by rickhumphries** [comment]
@btopro @mkwisc I've made a quick video to give an example of where we are with this at the moment:

https://www.youtube.com/watch?v=_r1gJb6K9A0

There's a few implementation points to discuss and things to be improved on UXwise but it's getting there. Implementation discussion points currently:
- The xAPI activity ID from H5P takes the url from the page that the activity is embedded on rather than the url of the 'master' copy set up in Media. There's pros and cons to this I think.
- An OpenBadge will only be awarded automatically once a cron has run through the Learning Locker report export which is done nightly. Ideally we could do with some sort of real-time API or something here so a student knows immediately once they've earned a badge but unfortunately that's out of scope of this project at the moment. A student should receive a notification the next time they log in though.   
- H5P only generates two verbs currently. Completed and Passed. Currently we set the verb as 'passed' if 100% is achieved in an activity, and 'completed' if not. I still need to go through and test a few more activity types to see how statements are produced in these.
- The Open Badge 'Criteria' and 'Evidence' URLs could do with being thought out a bit more. Currently a URL is manually entered. I guess this is OK for criteria, but for evidence you would really want the only the xAPI statements recorded by a student that have contributed towards the badge to be generated automatically and attached as a page here. 
- The way that we award Badges based on xAPI statements is implemented different to here - https://github.com/ht2/BadgesCoP. Ideally we'd want to comply with this in the future, but this is a good starting point, since BadgesCoP is still in development.

**Comment by mkwisc** [comment]
Awesome work @rickhumphries ! Thanks for demoing this.

**Comment by btopro** [comment]
AWESOME stuff; just gotta stitch all the UX together :)

**Comment by btopro** [comment]
two other threads covering this, converging into #72
